---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify: restart nginx

- name: Allow "Nginx Full" through UFW
  ufw:
    rule: allow
    name: "Nginx Full"
