---
- name: Install python package passlib
  pip:
    name: passlib
    state: present

- name: Create new user "{{ new_user }}"
  user:
    name: "{{ new_user }}"
    shell: /bin/bash
    password: "{{ mysql_root_password | password_hash('sha512') }}"
    state: present
    create_home: yes

- name: Add user "{{ new_user }}" to sudo group
  user:
    name: "{{ new_user }}"
    groups: sudo
    append: yes
